class Latihan1{
  public static void main(String[] args){
    int[] numbers = new int[10]; // menginisiasi array of int dengan panjang 10
    System.out.println(numbers[5]); // menampilkan 0 , karena isinya nol semua (formatnya integer)

    System.out.println("====================");
    String[] strList = new String[5];// inisiasi array String dengan panjang 5
    System.out.println(strList[0]);// menampilkan  , karena isinya null semua (formatnya string)

    System.out.println("====================");
    int[] primes = {2,3,5,7,11}; //menginisiasi array of int dengan initial values
    System.out.println(primes[2]);// menampilkan 5, karena 0,1,2 -> 2,3,5

    System.out.println("====================");
    String[] animals = {"cat","bird","tiger"}; // ...
    System.out.println(animals[1]); // menampilkan ...
    animals[0] = "fish"; //mengganti elemen index ke 0
    System.out.println(animals[1]); // menampilkan ...
    System.out.println(animals[0]); // menampilkan ...

    System.out.println("====================");
    String str  = "a b c d";
    String[] splitstr = str.split(" "); //menginisiasi array of String dari method split
    System.out.println(splitstr[3]);// menampilkan ...
    splitstr[3] = "new"; //...

    int[][] points = new int[4][4];     // array of int 2 dimensi dengan panjang 4, dan lebar 4 seperti papan catur
    System.out.println(points[0][0]);  //....
    points[0][1] = 5;  //...
    points[1] = new int[2]; //...
    // points[2] = {1,2,3};    //...
    // Int[] sesuatu = {1,2,3};  //....
    System.out.println(points[0][5]); //...

  }
}
